interface SampleEmail {
  subject: string;
  body: string;
  personalizationNotes: string[];
}

interface Props {
  email?: Partial<SampleEmail>;
  loading?: boolean;
}

export function SampleEmailCard({ email, loading }: Props) {
  if (loading) {
    return (
      <div className="rounded-xl border border-brand-border bg-brand-surface-elevated p-5 animate-pulse space-y-3 my-2">
        <div className="h-4 bg-brand-border rounded w-1/3" />
        <div className="h-3 bg-brand-border rounded w-full" />
        <div className="h-3 bg-brand-border rounded w-5/6" />
        <div className="h-3 bg-brand-border rounded w-4/5" />
      </div>
    );
  }

  if (!email?.subject) return null;

  return (
    <div className="rounded-xl border border-brand-primary/30 bg-brand-surface-elevated p-5 my-2 space-y-4">
      <div className="flex items-center gap-2">
        <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-brand-primary/20 text-brand-primary-light text-xs font-semibold">
          <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" aria-hidden="true">
            <rect width="20" height="16" x="2" y="4" rx="2" />
            <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
          </svg>
          Sample Cold Email
        </span>
        <span className="text-xs text-brand-text-muted">AI-generated by Houdiny</span>
      </div>

      <div>
        <p className="text-xs text-brand-text-muted mb-1 font-semibold uppercase tracking-wide">Subject</p>
        <p className="text-sm font-semibold text-brand-text">{email.subject}</p>
      </div>

      <div>
        <p className="text-xs text-brand-text-muted mb-2 font-semibold uppercase tracking-wide">Body</p>
        <div className="bg-brand-surface rounded-lg border border-brand-border p-4">
          <pre className="text-sm text-brand-text-secondary whitespace-pre-wrap font-sans leading-relaxed">
            {email.body}
          </pre>
        </div>
      </div>

      {email.personalizationNotes && email.personalizationNotes.length > 0 && (
        <div>
          <p className="text-xs text-brand-text-muted mb-2 font-semibold uppercase tracking-wide">Personalization Notes</p>
          <ul className="space-y-1">
            {email.personalizationNotes.map((note, i) => (
              <li key={i} className="flex items-start gap-2 text-xs text-brand-text-secondary">
                <span className="mt-0.5 w-1.5 h-1.5 rounded-full bg-brand-primary-light shrink-0" />
                {note}
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}
